apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  timeoutForControlPlane: 4m0s
certificatesDir: /etc/kubernetes/pki
controlPlaneEndpoint: "${KUBEAPI}:${FRONTENDPORT}"
clusterName: kubernetes
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kubernetesVersion: v1.22.2
networking:
  dnsDomain: cluster.local
  podSubnet: ${PODSUBNET}
  serviceSubnet: ${SVCSUBNET}
scheduler: {}
